# include: package:analysis_options/analysis_options.yaml  # Uncomment this line if you want to include default Dart analysis options

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
