name: Flutter Web CI/CD

on:
  push:
    branches:
      - lab7
  pull_request:
    branches:
      - lab7

jobs:
  build:
    runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - run: flutter pub get
      - run: flutter analyze --no-fatal-warnings --no-fatal-infos lib/livecoding/cicd

      - run: flutter build web --release -t lib/templates/lab7/main.dart

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web