name: Build Web

linter:
  rules:

analyzer:
  exclude:
    - lib/templates/lab7/main.dart

on: 
  push:
    branches:
      - lab7
  pull_request:
    branches:
      - lab7

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter pub get

      - run: flutter test test/test.dart

      - run: flutter analyze --no-fatal-warnings --no-fatal-infos lib/templates/lab7/

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /Sum24FlutterCourse/
          customArgs: "lib/templates/lab7/main.dart"
